apiVersion: v1
kind: Pod
metadata:
  name: main
  labels:
    type: main
spec:
  nodeSelector:
    a-team: "1"
  containers:
    - name: container
      image: kubetm/app
      terminationGracePeriodSeconds: 0
