apiVersion: v1
kind: Pod
metadata:
  name: sub
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: a-team
          labelSelector:
            matchExpressions:
              - key: type
                operator: In
                values: [main]
  containers:
    - name: container
      image: tmkube/app
      terminationGracePeriodSeconds: 0
